version: 2.1

orbs:
  orb-tools: circleci/orb-tools@12.0
  shellcheck: circleci/shellcheck@3.2.0

workflows:
  publish-dev-orb:
    when:
      not:
        equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - orb-tools/lint
      - shellcheck/check:
          dir: ./src/scripts
      - orb-tools/pack
      - orb-tools/publish:
          context: dev
          requires: 
            - orb-tools/pack
          vcs_type: << pipeline.project.type >>
          orb_name: NicolasMunoz13/nicolaskcorb
          pub_type: dev